# -*- coding: utf-8 -*-
"""W8TDS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tBYKbQVaWanBFfeHWGuy2aIuhUuEaERC
"""

import streamlit as st

st.title("21F1007104 - Week 8 - TDS - SIMPLE Streamlit App")

st.text("Enter a number in the box below")
n1 = st.number_input('Number',step=1)
st.text("Enter a number in the box below")
n2 = st.number_input('Number',step=1)

st.write(f'{n1}+{n2} = {n1+n2}')